meta_product_name: "The Clementine Project"
meta_title: "The Clementine Project - Women of Kigali"
meta_description: "Unser Projekt unterstützt Schneiderin in Ruanda sich einen unabhängigen und selbstständigen Lebensunterhalt zu verdienen."
meta_image: "cover.png"
# twitter_account: "@product_twitter_account" # required for Twitter Cards